---
title: Stackbit Azimuth Theme
baseURL: "/"
params:
  palette: blue
  header:
    title: Azimuth
    logo_img: images/logo.png
    has_nav: true
    menu:
      actions:
      - label: Sign Up
        url: "/signup"
  footer:
    logo_img: images/logo_alt.png
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Company
    has_social: true
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; Stackbit. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - name: Features
    weight: 2
  - name: Pricing
    weight: 3
  - name: Style Guide
    weight: 4
  - name: Home
    weight: 1
  secondary:
  - name: Sign Up
    weight: 1
  - name: Blog
    weight: 3
  - name: Contact
    weight: 4
  - name: About Us
    weight: 2
